"""
Supervisor Agent module.
Responsible for overseeing the TDD process and coordinating agents.
"""
from typing import Dict, Any
from .core import Agent, AgentConfig
from .tester_agent import TesterAgent
from .implementer_agent import ImplementerAgent
from .refactorer_agent import RefactorerAgent
import os
from pathlib import Path
import git


class SupervisorAgent(Agent):
    """Agent responsible for supervising the TDD process."""
    
    def __init__(self, work_dir: str, kata_description: str, config: AgentConfig):
        super().__init__("Supervisor", work_dir, kata_description)
        self.config = config
        self.cycle_count = 0
        
        # Initialize git repository if it doesn't exist
        try:
            self.repo = git.Repo(work_dir)
        except git.InvalidGitRepositoryError:
            self.repo = git.Repo.init(work_dir)
            # Make initial commit if repo is empty
            if not self.repo.heads:
                with open(os.path.join(work_dir, "README.md"), "w") as f:
                    f.write("# Kata Project\n\nThis project was generated by agentic-tdd.")
                self.repo.index.add(["README.md"])
                self.repo.index.commit("Initial commit: project setup")
    
    def execute(self) -> Dict[str, Any]:
        """Execute the supervisor agent's role: coordinate the TDD process."""
        print(f"{self.name}: Starting TDD process...")
        
        # Run the TDD cycle for the configured number of iterations
        for cycle in range(self.config.max_cycles):
            self.cycle_count = cycle + 1
            print(f"\n--- Cycle {self.cycle_count} ---")
            
            # Execute the TDD cycle: Test -> Implement -> Refactor
            cycle_result = self._execute_tdd_cycle()
            
            if not cycle_result['success']:
                print(f"{self.name}: TDD cycle failed: {cycle_result['message']}")
                break
            
            print(f"{self.name}: Completed cycle {self.cycle_count}")
        
        return {
            'success': True,
            'cycles_completed': self.cycle_count,
            'message': f"Supervisor agent completed {self.cycle_count} cycles"
        }
    
    def _execute_tdd_cycle(self) -> Dict[str, Any]:
        """Execute one full TDD cycle."""
        try:
            # 1. Tester Agent: Write a failing test
            tester = TesterAgent(str(self.work_dir), self.kata_description, self.config)
            test_result = tester.execute()
            print(f"{self.name}: {test_result['message']}")
            
            # Commit tester changes with descriptive message
            self._commit_agent_changes("test", f"test: add failing test for cycle {self.cycle_count}")
            
            # 2. Implementer Agent: Make the test pass
            implementer = ImplementerAgent(str(self.work_dir), self.kata_description, self.config)
            impl_result = implementer.execute()
            print(f"{self.name}: {impl_result['message']}")
            
            # Commit implementer changes with descriptive message
            self._commit_agent_changes("implement", f"feat: implement code to pass test in cycle {self.cycle_count}")
            
            # 3. Refactorer Agent: Improve code quality
            refactorer = RefactorerAgent(str(self.work_dir), self.kata_description, self.config)
            refactor_result = refactorer.execute()
            print(f"{self.name}: {refactor_result['message']}")
            
            # Commit refactorer changes with descriptive message
            self._commit_agent_changes("refactor", f"refactor: improve code quality after cycle {self.cycle_count}")
            
            return {
                'success': True,
                'message': f"TDD cycle {self.cycle_count} completed successfully"
            }
        except Exception as e:
            return {
                'success': False,
                'message': f"TDD cycle failed with error: {str(e)}"
            }
    
    def _commit_agent_changes(self, agent_type: str, message: str):
        """Commit changes made by a specific agent with descriptive message."""
        try:
            # Add all changes
            self.repo.git.add(A=True)
            
            # Commit if there are changes
            if self.repo.is_dirty():
                self.repo.index.commit(message)
                print(f"{self.name}: Committed {agent_type} changes: {message}")
        except Exception as e:
            print(f"{self.name}: Failed to commit {agent_type} changes: {str(e)}")
